name: Node js CI

on: [ push ]

jobs:
  
   build:
     runs-on: windows-latest

     strategy:
       matrix:
         node-version: 18

     steps:
     -uses: actions/checkout@v2

     name: run a multiple line script
       run:
         echo Add another actions to build
         echo test, and deploy your project
